name: AuthMe
author: Xephi59, Possible
website: http://dev.bukkit.org/bukkit-plugins/authme-reloaded/
description: AuthMe prevents people, which aren't logged in, from doing stuff like placing blocks, moving, typing commands or seeing the inventory of the current player.
main: uk.org.whoami.authme.AuthMe
version: 3.0-dev
softdepend: [Vault, ChestShop, Spout, Multiverse-Core, Notifications, Citizens, CombatTag, Essentials, EssentialsSpawn]
commands:
    register:
        description: Register an account
        usage: /register password confirmpassword
        aliases: reg
    login:
        description: Login into a account
        usage: /login password
        aliases: l
    changepassword:
        description: Change password of a account
        usage: /changepassword oldPassword newPassword
    logout:
        description: Logout
        usage: /logout
    unregister:
        description: unregister your account
        usage: /unregister password    
    passpartu:
        description: compare passpartu token
        usage: /passpartu token          
    authme:
        description: AuthMe op commands
        usage: '/authme reload|register playername password|changepassword playername password|unregister playername|version'
    email:
        description: Add Email or recover password
        usage: '/email add your@email.com your@email.com|change oldEmail newEmail|recovery your@email.com'
    captcha:
        description: Captcha
        usage: /captcha theCaptcha
permissions:
    authme.player.*:
        description: Gives access to all authme player commands
        default: true
        children:
            authme.register: true
            authme.login: true
            authme.changepassword: true
            authme.logout: true
            authme.unregister: true
            authme.passpartu: true
            authme.l: true
            authme.reg: true
    authme.admin.*:
         description: Gives access to all authme admin commands
         children:
             authme.admin.reload: true
             authme.admin.register: true
             authme.admin.changepassword: true
             authme.admin.unregister: true
             authme.admin.purge: true
             authme.seeOtherAccounts: true
             authme.admin.lastlogin: true
             authme.admin.getemail: true
             authme.admin.chgemail: true
    authme.register:
        description: Register an account
        default: true
    authme.login:
        description: Login into a account
        default: true
    authme.changepassword:
        description: Change password of a account
        default: true
    authme.logout:
        description: Logout
        default: true
    authme.email:
        description: Email
        default: true
    authme.passpartu:
        description: passpartu
        default: true        
    authme.allow2accounts:
        description: allow more accounts for same ip
        default: false
    authme.seeOtherAccounts:
        description: display other accounts about a player when he logs in
        default: false
    authme.unregister:
        description: unregister your account
        default: true
    authme.admin.reload:
        description: AuthMe reload commands
        default: op
    authme.admin.register:
        description: AuthMe register command
        default: op
    authme.admin.changepassword:
        description: AuthMe changepassword command
        default: op
    authme.admin.unregister:
        description: AuthMe unregister command
        default: op
    authme.admin.purge:
        description: AuthMe unregister command
        default: op
    authme.admin.convertflattosql:
        description: Convert File to Sql method
        default: op
    authme.admin.convertfromrakamak:
        description: Convert from Rakamak database to AuthMe
        default: op
    authme.admin.lastlogin:
        description: Get last login date about a player
        default: op
    authme.admin.getemail:
        description: Get last email about a player
        default: op
    authme.admin.chgemail:
        description: Change a player email
        default: op
    authme.admin.accounts:
        description: Display Players Accounts
        default: op
    authme.admin.xauthimport:
        description: Import xAuth Database to AuthMe Database
        default: op
    authme.captcha:
        description: Captcha
        default: true
    authme.admin.setspawn:
        description: Set the AuthMe spawn point
        default: op
    authme.admin.spawn:
        description: Teleport to AuthMe spawn point
        default: op
    authme.vip:
        description: Allow vip slot when the server is full
        default: op
    authme.admin.purgebannedplayers:
        description: Purge banned players
        default: op
    authme.admin.flattosqlite:
        description: Convert File to Sqlite method
        default: op